export { useRoutesHome } from "./src/routes/routes";

export { AppRouter } from "./src/router/AppRouter";
// export { PrivateRoute } from "./src/router/PrivateRouter";
// export { PublicRoute } from "./src/router/PublicRouter";
// export { PrivateRouteAdmin } from "./src/router/PrivateRouter";
// export { PublicRouteAdmin } from "./src/router/PublicRouter";
// export { PrivateRouteAdvisor } from "./src/router/PrivateRouter";
// export { PublicRouteAdvisor } from "./src/router/PublicRouter";

export { Home } from "./src/views/home/Home";
export { About } from "./src/views/home/about/About";
export { HomeAbout } from "./src/views/home/about/HomeAbout";
export { Mision } from "./src/views/home/about/Mision";
export { Vision } from "./src/views/home/about/Vision";
export { Values } from "./src/views/home/about/Values";
export { Targets } from "./src/views/home/about/Targets";
export { QualityPolicy } from "./src/views/home/about/QualityPolicy";
export { Immovables } from "./src/views/home/properties/Immovables";
export { Coverage } from "./src/views/home/coverage/Coverage";
export { HelpCenter } from "./src/views/home/helpcenter/HelpCenter";
export { Contact } from "./src/views/home/contact/Contact";
export { Pqrs } from "./src/views/home/helpcenter/Pqrs";
export { PrivPoly } from "./src/views/home/legal/PrivPoly";
export { DataTreathment } from "./src/views/home/legal/DataTreathment";                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
export { CommerceIndustry } from "./src/views/home/legal/CommerceIndustry";                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
export { Sales } from "./src/views/home/sales/Sales";                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
export { Leases } from "./src/views/home/leases/Leases";                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
export { PropertyList } from "./src/views/home/properties/PropertyList";        
export { RecentAdded } from "./src/views/home/leases/RecentAdded";                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
export { Services } from "./src/views/home/Services/Services";

export { Register } from "./src/views/home/auth/Register";                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
export { Login } from "./src/views/home/auth/Login";
export { AuthHome } from "./src/views/home/auth/AuthHome";  


export { CardProperty } from "./src/components/CardProperty";
export { CardServices } from "./src/components/CardServices";
export { CardLeases } from "./src/components/CardLeases";                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
export { Footer } from "./src/components/Footer";                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
export { Header } from "./src/components/Header";   
export { BaseButton } from "./src/components/BaseButton";                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
export { BaseInput } from "./src/components/BaseInput";                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
export { BaseInputSelect } from "./src/components/BaseInputSelect";
export { Rating } from "./src/components/Rating";
export { Spinner } from "./src/components/Spinner";
export { Loader } from "./src/components/Loader";
export { Pagination } from "./src/components/Pagination";
export { ScreenResolution } from "./src/components/ScreenResolution";
export { Table } from "./src/components/Table";


export { Statics } from "./src/views/admin/statics/Statics";
export { Reports } from "./src/views/admin/reports/Reports";
export { Users } from "./src/views/admin/users/Users";
export { Clients } from "./src/views/admin/users/Clients";
export { Advisors } from "./src/views/admin/users/Advisors";
export { PendingAdvisors } from "./src/views/admin/users/PendingAdvisors";
export { PendingClients } from "./src/views/admin/users/PendingClients";
export { UserStatuses } from "./src/views/admin/users/UserStatuses";
export { Comunications } from "./src/views/admin/comunications/Comunications";
export { Finances } from "./src/views/admin/finances/Finances";
export { Memberships } from "./src/views/admin/memberships/Memberships";
export { RecentProperties } from "./src/views/admin/properties/properties-recent/RecentProperties";
export { Settings } from "./src/views/admin/settings/Settings";
export { Validations } from "./src/views/admin/Validations/Validations";
export { ForRentPropertiesw } from "./src/views/admin/properties/properties-for-rent/ForRentPropertiesw";
export { LeasedProperties } from "./src/views/admin/leased/LeasedProperties";
export { Pending } from "./src/views/admin/properties/properties-status/Pending";
export { Approved } from "./src/views/admin/properties/properties-status/Approved";
export { Rejected } from "./src/views/admin/properties/properties-status/Rejected";
export { Properties } from "./src/views/admin/properties/Properties";
export { DetailSales } from "./src/views/admin/Sales/DetailSales";



export { ClientDashboard } from "./src/views/users/clients/ClientDashboard";
export { AdvisorDashboard } from "./src/views/users/advisors/AdvisorDashboard";

export { AdminHome } from "./src/views/admin/auth/AdminHome";
export { AdminDashboard } from "./src/views/admin/AdminDashboard";                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              

export { HomeLayout } from "./src/layouts/HomeLayout";
export { UserDashboardLayout } from "./src/layouts/UserDashboardLayout";
export { AdminDashboardLayout } from "./src/layouts/AdminDashboardLayout";
export { AdvisorDashboardLayout } from "./src/layouts/AdvisorDashboardLayout";
export { AuthLayout } from "./src/layouts/AuthLayout";